### ISSUE TITLE
what is ReceiveOptions?

### ISSUE THREAD

**Issue by chris-rutkowski** [TelegramBots/Telegram.Bot.Extensions.Polling#10]
Hey,

maybe it will be obvious, but just following your Readme compile tells me that ReceiveOptions does not exist in the current context without any resolution. Can you please advise?

**Comment by tuscen** [comment]
Sorry for the misunderstanding. Readme is for a newer unreleased version.

**Comment by chris-rutkowski** [comment]
Thank you @tuscen . 
Would you share in that case how `StartReceiving` method should be called for me and other users?
Because right now the library https://github.com/TelegramBots/Telegram.Bot gives me plenty of warnings about deprecated calls.

What I'm interested in is handling messages from users, callback queries and any errors.

Really appreciate getting rid of these warnings.

Would you share when the upcoming version is going to be released?

**Comment by tuscen** [comment]
@chris-rutkowski I've released the first alpha of the polling package yesterday so you can now test the latest release.

**Comment by danijerez** [comment]
The same is still happening to me in the latest version, what should I do to use ReceiveOptions?

**Comment by tuscen** [comment]
The latest version is 1.0.0-alpha.1 and `ReceiverOptions` is there
